/**
 * Agent-loop OTel metrics, exported through the global MeterProvider.
 *
 * Each LLM call records its token counters when it completes, the forced
 * wrap-up included. Thus a run that throws keeps the counts of the calls that
 * completed before the throw:
 *   - cortex.harness.agent.input_tokens — input tokens billed, cache reads
 *     included.
 *   - cortex.harness.agent.output_tokens — output tokens generated.
 *   - cortex.harness.agent.cache_read_tokens — prefix tokens served from the
 *     prompt cache.
 *   - cortex.harness.agent.cache_write_tokens — prefix tokens written into it
 *     (billed at a premium; only pays off once something reads it).
 *   - cortex.harness.agent.reasoning_tokens — reasoning tokens, as the provider
 *     reports them.
 *
 * Each token counter carries three labels:
 *   - agent_id — the agent id of the usage record of the call.
 *   - model — the served model of the response. Absent when the response
 *     reports no served model.
 *   - provider — the provider id of the bound model, for example
 *     `anthropic.messages`. Absent when the response names no provider.
 *
 * Providers do not agree on whether `outputTokens` includes the reasoning
 * tokens. The `provider` label keeps each reasoning series to one provider,
 * thus one series sums figures of one meaning.
 *
 * Each `runAgent` completion also records, with the `agent_id` label only:
 *   - cortex.harness.agent.iterations — histogram of LLM iterations per run.
 *     A creeping distribution is a leading indicator of prompt drift.
 *   - cortex.harness.agent.cap_hits — counter, incremented once per run that
 *     exhausted `maxIterations` and took the forced wrap-up path.
 *
 * The two cache counters are what make prompt caching *observable*: the hit
 * rate for an agent type is `cache_read_tokens / input_tokens` (the harness's
 * `inputTokens` is the total billed prefix, cache reads included). A flat-zero
 * `cache_read_tokens` against a non-zero `cache_write_tokens` means every write
 * is being thrown away — either a cache defeater is shifting the prefix (see
 * `providers/prompt-cache.ts`) or the endpoint ignores cache directives.
 *
 * Token counters are recorded only from what a provider actually reports; a
 * provider that reports no usage contributes nothing rather than zero.
 *
 * Instruments are created lazily on first use so the loop binds to whatever
 * `MeterProvider` is registered globally at runtime (production: the OTLP
 * exporter from `harness/lib/otel.ts`; tests: an in-memory reader).
 */

import { type Attributes, type Counter, type Histogram, metrics } from "@opentelemetry/api";

import { TOKEN_USAGE_FIELDS, type TokenUsageField, type TokenUsageRollup } from "../contracts/usage.js";
import type { ChatResponse, ChatUsage } from "../providers/types.js";

interface Instruments {
    readonly iterations: Histogram;
    readonly capHits: Counter;
    readonly inputTokens: Counter;
    readonly outputTokens: Counter;
    readonly cacheReadTokens: Counter;
    readonly cacheWriteTokens: Counter;
    readonly reasoningTokens: Counter;
}

let instruments: Instruments | undefined;

function getInstruments(): Instruments {
    if (instruments === undefined) {
        const meter = metrics.getMeter("cortex.harness.loop");
        instruments = {
            iterations: meter.createHistogram("cortex.harness.agent.iterations", {
                description: "LLM iterations executed per runAgent completion",
                unit: "{iteration}",
            }),
            capHits: meter.createCounter("cortex.harness.agent.cap_hits", {
                description: "runAgent completions that exhausted maxIterations and took the " + "forced wrap-up path",
            }),
            inputTokens: meter.createCounter("cortex.harness.agent.input_tokens", {
                description: "Input tokens billed for each completed LLM call, cache reads included",
                unit: "{token}",
            }),
            outputTokens: meter.createCounter("cortex.harness.agent.output_tokens", {
                description: "Output tokens generated by each completed LLM call",
                unit: "{token}",
            }),
            cacheReadTokens: meter.createCounter("cortex.harness.agent.cache_read_tokens", {
                description: "Prompt-prefix tokens served from the provider's prompt cache",
                unit: "{token}",
            }),
            cacheWriteTokens: meter.createCounter("cortex.harness.agent.cache_write_tokens", {
                description: "Prompt-prefix tokens written into the provider's prompt cache",
                unit: "{token}",
            }),
            reasoningTokens: meter.createCounter("cortex.harness.agent.reasoning_tokens", {
                description: "Reasoning tokens of each completed LLM call, as the provider reports them",
                unit: "{token}",
            }),
        };
    }
    return instruments;
}

/**
 * Token usage summed over LLM calls: the calls of one `runAgent`, or the calls
 * of a whole turn. Each field stays `undefined` until some call actually reports
 * it, so "the provider told us nothing" never masquerades as a measured zero.
 *
 * The same figures also grow the counters of each call (see the module header).
 * A rollup sums `reasoningTokens` as the providers report it. The reasoning
 * counter carries the `provider` label, because providers do not agree on
 * whether `outputTokens` includes the reasoning tokens.
 */
export interface AgentRunUsage {
    inputTokens?: number;
    outputTokens?: number;
    cacheCreationInputTokens?: number;
    cacheReadInputTokens?: number;
    reasoningTokens?: number;
}

// This module is where the three declarations of the usage shape meet: it folds
// a `ChatUsage` into an `AgentRunUsage` by iterating `TOKEN_USAGE_FIELDS`, the
// contracts-side list the wire rollup is defined by. `contracts/` cannot import
// either of these types (it must stay free of the loop and the provider seam),
// so the assertions pinning them to that list live here, on the consuming side.
// Key-set equality in both directions is what makes them bite: an `extends`
// check would accept a shape carrying an extra count, which is precisely the
// drift that leaves a new field silently unfolded and unreported.
type _AssertRunUsageFields = Exclude<keyof AgentRunUsage, TokenUsageField> | Exclude<TokenUsageField, keyof AgentRunUsage> extends never ? true : never;
const _assertRunUsageFields: _AssertRunUsageFields = true;

/** Fold one call's reported usage into a run's running total. */
export function addChatUsage(total: AgentRunUsage, usage: ChatUsage | undefined): void {
    if (usage === undefined) return;
    for (const key of TOKEN_USAGE_FIELDS) {
        const value = usage[key];
        if (value !== undefined) total[key] = (total[key] ?? 0) + value;
    }
}

/**
 * Whether anything was ever folded in. An accumulator no call reported into
 * stays empty, and the surfaces that carry a rollup must then carry none at
 * all rather than an all-zero figure.
 *
 * It also accepts the wire-shaped `TokenUsageRollup`, so a surface that RECEIVES
 * a rollup (thread history storing a turn's) decides "reported nothing" with the
 * same predicate the loop used to decide whether to emit one. Restating the rule
 * at either end is how the two would come to disagree.
 */
export function hasReportedUsage(usage: AgentRunUsage | ChatUsage | TokenUsageRollup | undefined): boolean {
    if (usage === undefined) return false;
    return Object.values(usage).some((value) => value !== undefined);
}

/**
 * Record the token counters of one completed LLM call.
 *
 * Each field that the response reports grows its counter. An absent field grows
 * nothing, not even by zero. A label whose value the response does not give is
 * omitted.
 */
export function recordChatCall(call: { readonly agentId: string; readonly response: ChatResponse }): void {
    const { usage, servedModelId, provider } = call.response;
    if (usage === undefined) return;
    const { inputTokens, outputTokens, cacheReadTokens, cacheWriteTokens, reasoningTokens } = getInstruments();
    const attributes: Attributes = {
        agent_id: call.agentId,
        ...(servedModelId === undefined ? {} : { model: servedModelId }),
        ...(provider === undefined ? {} : { provider }),
    };
    if (usage.inputTokens !== undefined) inputTokens.add(usage.inputTokens, attributes);
    if (usage.outputTokens !== undefined) outputTokens.add(usage.outputTokens, attributes);
    if (usage.cacheReadInputTokens !== undefined) cacheReadTokens.add(usage.cacheReadInputTokens, attributes);
    if (usage.cacheCreationInputTokens !== undefined) cacheWriteTokens.add(usage.cacheCreationInputTokens, attributes);
    if (usage.reasoningTokens !== undefined) reasoningTokens.add(usage.reasoningTokens, attributes);
}

/** Record one completed `runAgent` invocation. */
export function recordAgentRun(run: { readonly agentId: string; readonly iterations: number; readonly cappedOut: boolean }): void {
    const { iterations, capHits } = getInstruments();
    const attributes = { agent_id: run.agentId };
    iterations.record(run.iterations, attributes);
    if (run.cappedOut) capHits.add(1, attributes);
}

/**
 * Drop the memoized instruments so the next record rebinds to a
 * freshly-registered `MeterProvider`. Test-only — production registers its
 * provider once at startup.
 */
export function __resetMetricsForTest(): void {
    instruments = undefined;
}
