import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { Result, ok, err } from "neverthrow";
import { capture, type ContainerRuntime } from "../../lib/container.ts";
import { env } from "../../lib/env.ts";
import { CONTAINER_DATA_PATH, CONTAINER_PG_PORT, DEFAULT_IMAGE, type PostgresConnection, type PostgresError } from "./postgres_types.ts";

// Docker Compose orchestration for the inflexa infrastructure stack. Generates
// a compose file that places both the CLIProxyAPI proxy and the Postgres
// container on a shared `inflexa` network, so they can reach each other by
// service name (e.g. `inflexa-postgres:5432`) rather than host port mapping.
//
// Compose commands go through lib/container.ts's capture/inherit wrappers,
// which abstract `docker` vs `podman`. The compose subcommand (`docker compose`
// / `podman compose`) is a plugin of the same binary.

const PROXY_IMAGE = "eceasy/cli-proxy-api:latest";
const PROXY_CONFIG_PATH = "/CLIProxyAPI/config.yaml";
const PROXY_AUTH_DIR = "/root/.cli-proxy-api";

// Container and network names are environment-aware: `inflexa-*` in production
// builds, `inflexa-dev-*` in dev runs. This prevents a dev session's containers
// from colliding with (or shadowing) a user's installed binary's containers.
const PREFIX = env.isDev ? "inflexa-dev" : "inflexa";
export const PROXY_CONTAINER_NAME = `${PREFIX}-cliproxy`;
export const POSTGRES_CONTAINER_NAME = `${PREFIX}-postgres`;
const NETWORK_NAME = PREFIX;

/**
 * Generate a Docker Compose file defining both services on a shared network.
 * The compose file is YAML; we template it as a string to avoid a YAML dep.
 */
export function generateComposeFile(conn: PostgresConnection): string {
    return `# Generated by inflexa setup — do not edit by hand.
# Regenerated on every setup run; manual changes will be overwritten.

name: ${PREFIX}
services:
  ${PROXY_CONTAINER_NAME}:
    image: ${PROXY_IMAGE}
    container_name: ${PROXY_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${env.cliproxyPort}:${env.cliproxyPort}"
    volumes:
      - "${env.cliproxyConfigPath}:${PROXY_CONFIG_PATH}"
      - "${env.cliproxyAuthDir}:${PROXY_AUTH_DIR}"
    networks:
      - ${NETWORK_NAME}

  ${POSTGRES_CONTAINER_NAME}:
    image: ${DEFAULT_IMAGE}
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${conn.port}:${CONTAINER_PG_PORT}"
    environment:
      POSTGRES_DB: "${conn.database}"
      POSTGRES_USER: "${conn.user}"
      POSTGRES_PASSWORD: "${conn.password}"
    volumes:
      - "${env.postgresDataDir}:${CONTAINER_DATA_PATH}"
    networks:
      - ${NETWORK_NAME}

networks:
  ${NETWORK_NAME}:
    driver: bridge
`;
}

/**
 * Write the compose file to `env.composeFilePath`. Creates parent dirs.
 * Returns a typed error so the caller can surface it without a try/catch.
 */
export function writeComposeFile(conn: PostgresConnection): Result<void, PostgresError> {
    return Result.fromThrowable(
        () => {
            mkdirSync(dirname(env.composeFilePath), { recursive: true });
            writeFileSync(env.composeFilePath, generateComposeFile(conn));
        },
        (cause): PostgresError => ({
            type: "container_start_failed",
            message: `Failed to write compose file: ${cause instanceof Error ? cause.message : String(cause)}`,
        }),
    )();
}

/**
 * Generate and write the compose file if it doesn't already exist, or
 * always regenerate it (idempotent — setup always regenerates).
 */
export function ensureComposeFile(conn: PostgresConnection): Result<void, PostgresError> {
    return writeComposeFile(conn);
}

function composeArgs(subcommand: string[]): string[] {
    return ["compose", "-f", env.composeFilePath, ...subcommand];
}

/**
 * Remove pre-existing standalone containers that would conflict with compose.
 * The prior iteration created `inflexa-cliproxy` and `inflexa-postgres` via
 * individual `docker run` calls; compose can't adopt them because they weren't
 * created by compose. We detect standalone containers by checking for the
 * absence of the `com.docker.compose.project` label that compose sets on
 * every container it manages.
 */
async function removeStandaloneContainers(rt: ContainerRuntime): Promise<void> {
    const names = [PROXY_CONTAINER_NAME, POSTGRES_CONTAINER_NAME];
    for (const name of names) {
        const { code, stdout } = await capture(rt, ["inspect", "--format", '{{index .Config.Labels "com.docker.compose.project"}}', name]);
        if (code !== 0) continue;
        // Empty label = standalone container (not created by compose).
        // Non-empty = compose-managed, leave it alone.
        if (stdout.trim() === "") {
            await capture(rt, ["rm", "-f", name]);
        }
    }
}

/** Start all services in the compose file (idempotent — already-running services are untouched). */
export async function composeUp(rt: ContainerRuntime): Promise<Result<void, PostgresError>> {
    // Migrate: remove standalone containers from the prior iteration's `docker run` approach.
    // Without this, compose fails with "container name already in use" when a container
    // with the same name exists but wasn't created by compose.
    await removeStandaloneContainers(rt);

    const { code, stderr } = await capture(rt, composeArgs(["up", "-d"]));
    if (code !== 0) {
        return err({
            type: "container_start_failed",
            message: `Failed to start containers via compose.${stderr ? `\n  ${stderr.trim()}` : ""}\n  Check that ${rt.label} Compose is installed.`,
        });
    }
    return ok(undefined);
}

/** Pull all images in the compose file. */
export async function composePull(rt: ContainerRuntime): Promise<Result<void, PostgresError>> {
    const { code, stderr } = await capture(rt, composeArgs(["pull"]));
    if (code !== 0) {
        return err({
            type: "image_pull_failed",
            image: `${PROXY_IMAGE}, ${DEFAULT_IMAGE}`,
            message: `Failed to pull images via compose.${stderr ? `\n  ${stderr.trim()}` : ""}`,
        });
    }
    return ok(undefined);
}

/** Stop and remove all compose-managed containers and the shared network. */
export async function composeDown(rt: ContainerRuntime): Promise<Result<void, PostgresError>> {
    const { code, stderr } = await capture(rt, composeArgs(["down"]));
    if (code !== 0) {
        return err({
            type: "container_start_failed",
            message: `Failed to stop containers via compose.${stderr ? `\n  ${stderr.trim()}` : ""}`,
        });
    }
    return ok(undefined);
}

/** Check whether the compose subcommand is available for this runtime. */
export async function composeAvailable(rt: ContainerRuntime): Promise<boolean> {
    const { code } = await capture(rt, ["compose", "version"]);
    return code === 0;
}
