import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { Result, ok, err } from "neverthrow";
import { capture, inherit, type ContainerRuntime } from "../../lib/container.ts";
import { env } from "../../lib/env.ts";
import { CONTAINER_DATA_PATH, CONTAINER_PG_PORT, DEFAULT_IMAGE, type PostgresConnection, type PostgresError } from "./postgres_types.ts";

// Docker Compose orchestration for the inflexa infrastructure stack. Generates
// a compose file that places both the CLIProxyAPI proxy and the Postgres
// container on a shared `inflexa` network, so they can reach each other by
// service name (e.g. `inflexa-postgres:5432`) rather than host port mapping.
//
// Compose commands go through lib/container.ts's capture/inherit wrappers,
// which abstract `docker` vs `podman`. The compose subcommand (`docker compose`
// / `podman compose`) is a plugin of the same binary.

const PROXY_IMAGE = "eceasy/cli-proxy-api:latest";
const PROXY_CONFIG_PATH = "/CLIProxyAPI/config.yaml";
const PROXY_AUTH_DIR = "/root/.cli-proxy-api";

// Container and network names are environment-aware: `inflexa-*` in production
// builds, `inflexa-dev-*` in dev runs. This prevents a dev session's containers
// from colliding with (or shadowing) a user's installed binary's containers.
const PREFIX = env.isDevelopment ? "inflexa-dev" : "inflexa";
export const PROXY_CONTAINER_NAME = `${PREFIX}-cliproxy`;
export const POSTGRES_CONTAINER_NAME = `${PREFIX}-postgres`;
const NETWORK_NAME = PREFIX;

/** Escape a value for use inside a YAML double-quoted string (`"…"`). */
function escapeYaml(s: string): string {
    return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

/** The chat-backend connection modes that shape which services the compose file defines. */
export type ConnectionMode = "cliproxy" | "direct";

/**
 * Generate a Docker Compose file for the infra stack. The compose file is YAML; we template it as a
 * string to avoid a YAML dep.
 *
 * Connection-aware: `cliproxy` mode defines BOTH the CLIProxyAPI proxy and Postgres; `direct` mode
 * defines Postgres ONLY — a direct connection reaches the user's own endpoint with
 * `INFLEXA_MODEL_API_KEY`, so the managed proxy is never provisioned. Postgres is mode-independent.
 *
 * Invariant: `inflexa up`/`down` operate on WHICHEVER file already exists — they do not re-derive the
 * mode from a running file. The two authoritative regeneration points overwrite it with the current
 * mode on every run (`inflexa setup` and the TUI-launch gate `ensureProxyReady`, both via
 * {@link writeComposeFile}), so switching modes there rewrites the file coherently — proxy dropped for
 * direct, present again for cliproxy. `up` only generates when the file is missing
 * ({@link ensureComposeFile}), resolving the mode from config.
 */
export function generateComposeFile(conn: PostgresConnection, mode: ConnectionMode): string {
    const proxyService =
        mode === "cliproxy"
            ? `  ${PROXY_CONTAINER_NAME}:
    image: ${PROXY_IMAGE}
    container_name: ${PROXY_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${env.cliproxyPort}:${env.cliproxyPort}"
    volumes:
      - "${env.cliproxyConfigPath}:${PROXY_CONFIG_PATH}"
      - "${env.cliproxyAuthDir}:${PROXY_AUTH_DIR}"
    networks:
      - ${NETWORK_NAME}

`
            : "";
    return `# Generated by inflexa setup — do not edit by hand.
# Regenerated on every setup run; manual changes will be overwritten.

name: ${PREFIX}
services:
${proxyService}  ${POSTGRES_CONTAINER_NAME}:
    image: ${DEFAULT_IMAGE}
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${conn.port}:${CONTAINER_PG_PORT}"
    environment:
      POSTGRES_DB: "${escapeYaml(conn.database)}"
      POSTGRES_USER: "${escapeYaml(conn.user)}"
      POSTGRES_PASSWORD: "${escapeYaml(conn.password)}"
    volumes:
      - "${env.postgresDataDir}:${CONTAINER_DATA_PATH}"
    networks:
      - ${NETWORK_NAME}

networks:
  ${NETWORK_NAME}:
    driver: bridge
`;
}

/**
 * Write the compose file to `env.composeFilePath` for the given connection mode (see
 * {@link generateComposeFile} for the service set each mode defines). Creates parent dirs. Returns a
 * typed error so the caller can surface it without a try/catch. Always overwrites — this is an
 * authoritative regeneration point, so callers switching modes rewrite the file coherently.
 */
export function writeComposeFile(conn: PostgresConnection, mode: ConnectionMode): Result<void, PostgresError> {
    return Result.fromThrowable(
        () => {
            mkdirSync(dirname(env.composeFilePath), { recursive: true });
            writeFileSync(env.composeFilePath, generateComposeFile(conn, mode));
        },
        (cause): PostgresError => ({
            type: "compose_file_write_failed",
            message: `Failed to write compose file: ${cause instanceof Error ? cause.message : String(cause)}`,
        }),
    )();
}

/**
 * Generate and write the compose file if it doesn't already exist, for the given connection mode.
 * Setup and the TUI-launch gate use {@link writeComposeFile} directly to always regenerate; this
 * write-if-missing variant backs `inflexa up`, which operates on the existing file when present.
 */
export function ensureComposeFile(conn: PostgresConnection, mode: ConnectionMode): Result<void, PostgresError> {
    if (existsSync(env.composeFilePath)) return ok(undefined);
    return writeComposeFile(conn, mode);
}

function composeArgs(subcommand: string[]): string[] {
    return ["compose", "-f", env.composeFilePath, ...subcommand];
}

/** Start all services in the compose file (idempotent — already-running services are untouched). */
export async function composeUp(rt: ContainerRuntime): Promise<Result<void, PostgresError>> {
    const { code, stderr } = await capture(rt, composeArgs(["up", "-d"]));
    if (code !== 0) {
        return err({
            type: "container_start_failed",
            message: `Failed to start containers via compose.${stderr ? `\n  ${stderr.trim()}` : ""}\n  Check that ${rt.label} Compose is installed.`,
        });
    }
    return ok(undefined);
}

/** Pull all images in the compose file. */
export async function composePull(rt: ContainerRuntime): Promise<Result<void, PostgresError>> {
    const { code, stderr } = await capture(rt, composeArgs(["pull"]));
    if (code !== 0) {
        return err({
            type: "image_pull_failed",
            image: `${PROXY_IMAGE}, ${DEFAULT_IMAGE}`,
            message: `Failed to pull images via compose.${stderr ? `\n  ${stderr.trim()}` : ""}`,
        });
    }
    return ok(undefined);
}

/**
 * Pull all images in the compose file with inherited stdio so the user sees progress.
 * Used on the TUI launch path where silent buffering would make the app appear to hang.
 */
export async function composePullInteractive(rt: ContainerRuntime): Promise<Result<void, PostgresError>> {
    const code = await inherit(rt, composeArgs(["pull"]));
    if (code !== 0) {
        return err({
            type: "image_pull_failed",
            image: `${PROXY_IMAGE}, ${DEFAULT_IMAGE}`,
            message: `Failed to pull images via compose. Run \`${rt.bin} compose -f ${env.composeFilePath} pull\` manually.`,
        });
    }
    return ok(undefined);
}

/**
 * Pull any compose images that are not already present locally, streaming progress
 * to the terminal. Skips the network round-trip entirely when every image is cached.
 */
export async function composePullIfMissing(rt: ContainerRuntime, mode: ConnectionMode): Promise<Result<void, PostgresError>> {
    // Only the images the compose file for this mode actually defines: direct mode omits the proxy.
    const images = mode === "cliproxy" ? [PROXY_IMAGE, DEFAULT_IMAGE] : [DEFAULT_IMAGE];
    const missing = await Promise.all(
        images.map(async (image) => {
            const { code } = await capture(rt, ["image", "inspect", image]);
            return code !== 0;
        }),
    );
    if (!missing.some(Boolean)) return ok(undefined);

    console.log("  Pulling container images (this may take a moment)…");
    return composePullInteractive(rt);
}

/** Stop and remove all compose-managed containers and the shared network. */
export async function composeDown(rt: ContainerRuntime): Promise<Result<void, PostgresError>> {
    const { code, stderr } = await capture(rt, composeArgs(["down"]));
    if (code !== 0) {
        return err({
            type: "container_stop_failed",
            message: `Failed to stop containers via compose.${stderr ? `\n  ${stderr.trim()}` : ""}`,
        });
    }
    return ok(undefined);
}

/** Check whether the compose subcommand is available for this runtime. */
export async function composeAvailable(rt: ContainerRuntime): Promise<boolean> {
    const { code } = await capture(rt, ["compose", "version"]);
    return code === 0;
}
