/**
 * Report runner — orchestrates an iterative report build entirely in the
 * Cortex Node process. No sandbox, no Python.
 *
 * Lifecycle:
 *  1. Resolve version (latest + 1, or baseVersion + 1)
 *  2. Prepare version dir (mkdir, copy v{base}/report.html.j2, symlink ../assets)
 *  3. Construct the 4 custom report tools + the in-process versionFs surface;
 *     all of them close over the iteration's preview-dir state and a single
 *     `outcome: ReportOutcome | undefined` variable (the closure-state
 *     closure-state capture — see design.md Decision #9, mirrors
 *     `harness/tools/research/generate-plan.ts`'s
 *     `PlannerOutcome` capture).
 *  4. Build the `report-builder` AgentDefinition with that tool roster and
 *     drive it via `runAgent` + `passthroughStep`.
 *  5. Verify the closure-captured `outcome` is `{ ok: true, ... }` (else
 *     classify the failure, roll back the version dir, return a structured
 *     failure).
 *  6. Return success or a structured failure.
 *
 * Concurrency: per-previewId serialization via `withPreviewLock` so two
 * iterations on the same preview don't race on shared assets/.
 *
 * Billing: the report-builder's LLM calls flow through the `ChatProvider`
 * seam with `forSubAgent(session, REPORT_BUILDER_AGENT_ID)` — the provider's
 * lazy `resolveBilling` fires at the call site. No ALS, no fetch-patch
 * (Decision #6).
 *
 * Preview surface: the `preview_snapshot` and `mint_preview_url` tools mint
 * a content-server URL through the injected `PreviewPublisher` seam. The
 * managed publisher owns the short-lived host credential; the local default
 * returns "unavailable" so the report still builds without a hosted preview.
 */

import { copyFile, mkdir, readdir, rm, stat, symlink } from "node:fs/promises";
import { join } from "node:path";
import type { Pool } from "pg";

import { forSubAgent, type RequestSession } from "../auth/types.js";
import { runToTerminal } from "../loop/run-to-terminal.js";
import { passthroughStep } from "../loop/run-step.js";
import type { EmitFn } from "../loop/types.js";
import type { ChatProvider } from "../providers/types.js";
import { previewVersionDir, previewDir, latestPreviewVersion } from "../workspace/paths.js";
import { withPreviewLock } from "../tools/lib/preview-lock.js";
import {
    createBuildReportTool,
    createSubmitReportTool,
    createMintPreviewUrlTool,
    createPreviewSnapshotTool,
    createVersionFsTools,
    type ReportOutcome,
    type PreviewUrlCell,
} from "../tools/report/index.js";
import { createReportBuilderAgent, REPORT_BUILDER_AGENT_ID } from "../agents/report-builder.js";
import type { PreviewPublisher } from "../tools/report/preview-publisher.js";
import { createSkillTools } from "../tools/sandbox/skills.js";
import type { ChromeConfig } from "../lib/chrome.js";
import { createNoopLogger } from "../lib/console-logger.js";
import type { Logger } from "../lib/logger.js";

/** Skill pack the report-builder prompt directs the model to read (design-system reference). */
const REPORT_BUILDER_SKILLS = ["report-html"] as const;

const REPORT_AGENT_MAX_STEPS = 75;

export interface ReportRunnerDeps {
    /** Operational logging seam; omitted falls back to no-op. */
    readonly logger?: Logger;
    readonly provider: ChatProvider;
    readonly pool: Pool;
    /** Model id — provenance / metric label; provider owns the wire model. */
    readonly model: string;
    /** Root templates dir; `report-html` is joined onto it. */
    readonly templatesDir: string;
    /** Skills root; the report-builder gets read-only `report-html` skill tools. */
    readonly skillsDir: string;
    readonly chrome: ChromeConfig;
}

export interface ReportRunnerOptions {
    readonly resourceId: string;
    /** Absolute host root of the analysis's workspace tree (previews live inside it). */
    readonly workspaceRoot: string;
    readonly previews: PreviewPublisher;
    /** Preview group ID. Auto-generated by the tool layer if not provided. */
    readonly previewId: string;
    /** Base version to iterate from. Defaults to latest. */
    readonly baseVersion?: number;
    /**
     * Format the preview was built as. The tool boundary admits only `"html"`,
     * so no other value can reach a live iteration; the union stays wide because
     * previews persisted with a broader vocabulary must still parse. Read this
     * field as a record of what a preview is, not as a request for a renderer.
     */
    readonly format: "html" | "pdf";
    /** Prompt for the report-builder agent. */
    readonly prompt: string;
    /** Live chat session — derives the child agent's session via forSubAgent. */
    readonly session: RequestSession;
    /** Cancellation signal — propagates to the agent stream. */
    readonly signal: AbortSignal;
    /** Event sink — forwarded to the agent loop. */
    readonly emit: EmitFn;
}

export type ReportRunnerResult =
    | {
          ok: true;
          previewId: string;
          version: number;
          previewPath: string;
          durationMs: number;
          /** Caveats surfaced by the agent via submit_report. */
          notes: readonly string[];
      }
    | {
          ok: false;
          previewId: string;
          version: number;
          reason: string;
          errorKind: "render" | "submit" | "build" | "timeout" | "internal";
          durationMs: number;
      };

export async function runReportIteration(deps: ReportRunnerDeps, opts: ReportRunnerOptions): Promise<ReportRunnerResult> {
    const logger = (deps.logger ?? createNoopLogger()).named("report-runner").with({ previewId: opts.previewId });
    const startTime = performance.now();

    return withPreviewLock(opts.previewId, async () => {
        // ── Resolve version directories ───────────────────────────────
        const previewRootAbs = join(opts.workspaceRoot, previewDir(opts.previewId));
        let existingVersions: string[] = [];
        try {
            existingVersions = (await readdir(previewRootAbs, { withFileTypes: true })).filter((d) => d.isDirectory()).map((d) => d.name);
        } catch {
            /* dir doesn't exist yet */
        }

        const latestVer = latestPreviewVersion(existingVersions);
        const baseVer = opts.baseVersion ?? latestVer;
        const newVersion = Math.max(latestVer, baseVer) + 1;
        const versionDirRel = previewVersionDir(opts.previewId, newVersion);
        const versionDirAbs = join(opts.workspaceRoot, versionDirRel);
        const assetsDirAbs = join(previewRootAbs, "assets");

        // ── Prepare directories ───────────────────────────────────────
        try {
            await mkdir(versionDirAbs, { recursive: true });
            await mkdir(assetsDirAbs, { recursive: true });

            if (baseVer > 0) {
                const baseTemplate = join(opts.workspaceRoot, previewVersionDir(opts.previewId, baseVer), "report.html.j2");
                try {
                    await copyFile(baseTemplate, join(versionDirAbs, "report.html.j2"));
                } catch (err) {
                    const code = (err as NodeJS.ErrnoException).code;
                    if (code !== "ENOENT") throw err;
                    // Base version has no template — agent will author from scratch.
                }
            }

            // Symlink assets/ → ../assets so templates can reference assets/foo.csv
            // and the content-server resolves them through the version-dir prefix.
            const assetsSymlink = join(versionDirAbs, "assets");
            try {
                await symlink("../assets", assetsSymlink, "dir");
            } catch (err) {
                const code = (err as NodeJS.ErrnoException).code;
                if (code !== "EEXIST") throw err;
            }
        } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            return failure(opts.previewId, newVersion, `prepareVersionDir failed: ${msg}`, "internal", startTime);
        }

        // ── Closure-captured terminal-tool state (Decision #9) ─────────
        let outcome: ReportOutcome | undefined;
        const urlCell: PreviewUrlCell = { url: undefined, expiresAt: undefined };
        const templatesDir = join(deps.templatesDir, "report-html");

        const buildReportTool = createBuildReportTool({
            versionDir: versionDirAbs,
            templatesDir,
        });
        const submitReportTool = createSubmitReportTool({
            versionDir: versionDirAbs,
            assetsDir: assetsDirAbs,
            setOutcome: (v) => {
                outcome = v;
            },
        });

        const tools = [
            buildReportTool,
            submitReportTool,
            createMintPreviewUrlTool({
                resourceId: opts.resourceId,
                previewId: opts.previewId,
                currentVersion: newVersion,
                previews: opts.previews,
                urlCell,
            }),
            createPreviewSnapshotTool({
                resourceId: opts.resourceId,
                previewId: opts.previewId,
                currentVersion: newVersion,
                previews: opts.previews,
                urlCell,
                chrome: deps.chrome,
                logger,
            }),
            ...createVersionFsTools({ versionDir: versionDirAbs }),
            ...Object.values(createSkillTools({ skillsDir: deps.skillsDir, skills: [...REPORT_BUILDER_SKILLS] })),
        ];

        const agent = createReportBuilderAgent({ model: deps.model, tools });
        // The agent's runaway-guard takes precedence over the per-iteration cap.
        const cappedAgent = {
            ...agent,
            maxIterations: Math.min(agent.maxIterations, REPORT_AGENT_MAX_STEPS),
        };

        const childSession = forSubAgent(opts.session, REPORT_BUILDER_AGENT_ID);

        let agentError: string | undefined;
        try {
            await runToTerminal(
                cappedAgent,
                [{ role: "user", content: opts.prompt }],
                childSession,
                {
                    provider: deps.provider,
                    signal: opts.signal,
                    emit: opts.emit,
                    runStep: passthroughStep,
                },
                {
                    resolved: () => outcome !== undefined,
                    tools: [buildReportTool, submitReportTool],
                    nudge:
                        "You stopped without calling submit_report, so this report version " +
                        "was not recorded. Build the report if needed, then call " +
                        "submit_report now to finalize it.",
                },
            );
        } catch (err) {
            agentError = err instanceof Error ? err.message : String(err);
        }

        // ── Phantom-success guard ──────────────────────────────────────
        // submit-report claims ok but index.html doesn't exist or is empty.
        let phantomSuccess = false;
        if (outcome?.ok === true && !agentError) {
            try {
                const indexStat = await stat(join(versionDirAbs, "index.html"));
                if (!indexStat.isFile() || indexStat.size === 0) phantomSuccess = true;
            } catch {
                phantomSuccess = true;
            }
        }

        if (!outcome || agentError || phantomSuccess) {
            logger.warn("report.agent.finish", { version: newVersion, submitted: outcome?.ok === true, phantom: phantomSuccess, agentError });
            const { reason, errorKind } = classifyFailure({
                phantomSuccess,
                agentError,
                outcome,
            });
            // Roll back the version dir (assets are shared — leave them alone).
            try {
                await rm(versionDirAbs, { recursive: true, force: true });
            } catch (err) {
                logger.error("rollback failed", { versionDirAbs, ...logger.errorFields(err) });
            }
            return failure(opts.previewId, newVersion, reason, errorKind, startTime);
        }

        const durationMs = Math.round(performance.now() - startTime);
        return {
            ok: true,
            previewId: opts.previewId,
            version: newVersion,
            previewPath: `v${newVersion}/index.html`,
            durationMs,
            notes: outcome.notes,
        };
    });
}

function failure(
    previewId: string,
    version: number,
    reason: string,
    errorKind: "render" | "submit" | "build" | "timeout" | "internal",
    startTime: number,
): ReportRunnerResult {
    return {
        ok: false,
        previewId,
        version,
        reason,
        errorKind,
        durationMs: Math.round(performance.now() - startTime),
    };
}

interface FailureSignals {
    phantomSuccess: boolean;
    agentError: string | undefined;
    outcome: ReportOutcome | undefined;
}

function classifyFailure(s: FailureSignals): {
    reason: string;
    errorKind: "submit" | "timeout" | "build";
} {
    if (s.phantomSuccess) {
        return {
            reason: "submit_report claimed ok but index.html is missing or empty",
            errorKind: "build",
        };
    }
    if (s.agentError) {
        return {
            reason: s.agentError,
            errorKind: /timeout/i.test(s.agentError) ? "timeout" : "submit",
        };
    }
    return {
        reason: "agent did not call submit_report — terminal outcome was never recorded",
        errorKind: "submit",
    };
}
